print("Area and parimeter of rectangle")
print("----------------------------------")
width = input("Enter width : ")
height = input("Enter height : ")
area = float(width) + float(height)
p = 2*(float(width) + float(height))
print("----------------------------------")
print("Area = ",float(area))
print("Parimet = ",float(p))
